
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 100

[env]
# TERM = "xterm-256color"

[font]
# size = 12

[font.normal]
family = "Fira Code"
style = "Medium"

[font.offset]
y = 0

[keyboard]
bindings = [
{ action = "CreateNewWindow", key = "N", mods = "Command" },
{ mods = "Alt", key = "]", chars = "\u00dd" },
]


[window]
dynamic_title = true
dynamic_padding = true
resize_increments = true
option_as_alt = "OnlyLeft"

[general]
live_config_reload = true
import = ["alacritty.light.toml", "alacritty.vars.toml"]
