#!/usr/bin/env bash


# PPAs
sudo add-apt-repository -y -u ppa:dawidd0811/neofetch
sudo apt update
sudo apt install -y \
    neofetch

# console tools
sudo apt install -y \
    bc \
    dfc \
    htop \
    iotop \
    libsecret-tools \
    mc \
    moreutils \
    powertop \
    ranger \
    rar \
    tig \
    tlp \
    tmux \
    unzip \
    zip

# mopidy reqs
sudo apt install -y \
    python-pip

