#!/usr/bin/env bash

apt update

# console tools
apt install -y \
    bc \
    dfc \
    htop \
    iotop \
    mc \
    moreutils \
    powertop \
    ranger \
    rar \
    tig \
    tlp \
    tmux \
    unzip \
    zip

# mopidy reqs
sudo apt install -y \
    python-pip

# PPAs
add-apt-repository -y -u ppa:dawidd0811/neofetch
apt install -y \
    neofetch

