#!/usr/bin/env bash

# gui tools
apt install -y \
    blueman \
    compton \
    consolekit \
    dex \
    elementary-icon-theme \
    feh \
    fonts-noto \
    gir1.2-appindicator \
    hplip-gui \
    jq \
    libx11-protocol-other-perl \
    lightdm-gtk-greeter \
    lightdm \
    mpc \
    network-manager-openvpn-gnome \
    notification-daemon \
    pandoc \
    pulseaudio-module-bluetooth \
    redshift \
    rofi \
    rxvt-unicode-256color \
    shutter \
    stalonetray \
    suckless-tools \
    system-config-printer-gnome \
    thunar \
    vim-gtk \
    x11-apps \
    x11-utils \
    x11-xserver-utils \
    xautolock \
    xcape \
    xdo \
    xinit \
    xinput \
    xsel \
    xubuntu-icon-theme

pactl load-module module-bluetooth-discover

# bspwm, sxhkd reqs
apt install -y \
    build-essential \
    libxcb-ewmh-dev \
    libxcb-icccm4-dev \
    libxcb-keysyms1-dev \
    libxcb-randr0-dev \
    libxcb-util-dev \
    libxcb-xinerama0-dev

# i3lock-color reqs
apt install -y \
    libev-dev \
    libpam-dev \
    libxcb-composite0-dev \
    libxcb-dpms0-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev

# Debian packaging
apt install -y \
    devscripts

# RXVT mouse patch
apt build-dep -y \
    rxvt-unicode-256color

# PPA
add-apt-repository -y -u ppa:nilarimogard/webupd8
apt install -y \
    qt5ct \
    arc-theme \
    ncmpcpp

add-apt-repository -y -u ppa:bitcoin/bitcoin
apt install -y \
    bitcoin-qt
