#!/usr/bin/env bash

if ! which git >/dev/null; then
    echo "You need to install git to user this dotfiles repo. EXITING..."
    exit -1
fi

if [[ $(tmux -V) != 'tmux 2.0' ]]; then
    echo "This dotfiles repository is compatible with tmux 2.0 only. EXITING..."
fi

echo -n "Updating dotfiles... "
if [ -e "$HOME/.dotfiles" ]; then
    if [ -e "$HOME/.dotfiles/.repo.kmarc" ]; then
        (
        cd "$HOME/.dotfiles"
        git stash
        git pull --rebase
        git stash pop
        )
    else
        echo ""
        echo ".dotfiles directory exists and is not kmarc's. EXITING..."
        exit -1
    fi
else
    echo ""
    echo ".dotfiles directory not found. Installing... "
    git clone https://github.com/kmARC11/dotfiles.git "$HOME/.dotfiles"
    echo "DONE"
fi

echo -n "Setting up bash... "
SRC="source $HOME/.dotfiles/bashrc"
if ! grep -Fxq "$SRC" "$HOME/.bashrc"; then
    echo "$SRC" >> "$HOME/.bashrc"
    echo "DONE"
else
    echo "ALREADY SET UP"
fi

echo -n "Setting up tmux... "
if [ ! -e "$HOME/.tmux.conf" -a ! -e "$HOME/.tmux"  ]; then
    mkdir -p "$HOME/.tmux/plugins"
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    ln -s "$HOME/.dotfiles/tmux.conf" "$HOME/.tmux.conf"
    tmux run-shell "$HOME/.tmux/plugins/tpm/bindings/install_plugins"
    echo "DONE"
else
    echo "ALREADY SET UP"
fi

# @param dotfile name
# @param Human readable name
function _setupDotfile() {
    echo -n "Setting up ${2}..."
    if [ ! -e "$HOME/.${1}" ]; then
        ln -s "$HOME/.dotfiles/${1}" "$HOME/.${1}"
        echo "DONE"
    else
        echo "ALREADY SET UP"
    fi
}

_setupDotfile Xresources   Xresources
_setupDotfile vimperatorrc Vimperator
_setupDotfile toprc        top

unset _setupDotfile
