---

- name: Dotfiles
  hosts: localhost
  tasks:

    - name: Debug ansible distribution
      debug:
        var: ansible_distribution

    - name: Gather os specific variables
      include_vars: "requirements-{{ ansible_distribution | lower }}.yml"
      tags: always

    - name: Ensure directories exist
      file:
        path: '{{ item }}'
        state: directory
        mode: 0755
      with_items:
        - '$HOME/.fonts/'
        - '$HOME/.local/share/applications/'
        - '$HOME/.mutt/'
      tags: config

    - name: Install distribution specific packages
      package: name={{ item }}
      with_items: "{{ packages_base }}"
      become: true
      tags: packages

    #
    # vim
    #
    - name: Install kmarc's vim configuration
      git:
        repo: '{{ vim_repo }}'
        dest: '{{ vim_path }}'
        version: master
      tags: vim

    - name: Install vim plugins
      command: bash -cil 'vim -c ":PlugInstall" -c ":qa!"'
      changed_when: false
      tags: vim

    #
    # Dotfiles
    #
    - name: Create directories
      file:
        path: '$HOME/.{{ item }}'
        state: directory
        recurse: true
      with_items:
        - tmux/plugins
      tags: config

    - name: Symlink config files
      file:
        src: '{{ playbook_dir }}/{{ item }}'
        dest: '$HOME/.{{ item }}'
        state: link
      with_items:
        - Xresources
        - bashrc.kmarc
        - compton.conf
        - config/bspwm
        - config/polybar
        - config/sxhkd
        - gitconfig
        - mutt/muttrc._gmail_
        - mutt/muttrc._owa_
        - muttrc
        - rtorrent.rc
        - theme.rofi.Xresources
        - tmux.conf
        - toprc
        - xprofile
        - xstart
        - xstop
      tags: config

    - name: Symlink bin
      file:
        src: '{{ playbook_dir }}/{{ item }}'
        dest: '$HOME/{{ item }}'
        state: link
      with_items:
        - bin
      tags: config

    - name: Run scripts
      command: |
        bash -cil '\
          xrdb -load $HOME/.Xresources && \
          $HOME/bin/colorize.sh \
        '
      changed_when: false
      tags: config

    #
    # tmux tpm
    #
    - name: Install tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
      tags: config

    - name: Install tmux plugins
      shell: '~/.tmux/plugins/tpm/bin/install_plugins'
      tags: config
