if has('gui_running')
    if has('gui_macvim')
      set guifont=FiraCodeRoman-Medium:h12
    else
      set guifont=Fira\ Code\ Medium\ 10
    endif

    set guioptions=agit
    set linespace=1
endif
