#! /bin/bash
export PATH=$PATH:"$HOME/.local/bin"
wmname LG3D

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config focus_follows_pointer     true
bspc config focused_border_color      '#FFCC66'
bspc config presel_border_color       '#6699CC'
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config leaf_monocle              true
bspc config pointer_follows_focus     true
bspc config pointer_follows_monitor   true
bspc config auto_cancel               true



bspc rule -a Gimp desktop=^8 follow=on
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a Skype desktop=^7 split_dir=right split_ratio=0.3
bspc rule -a Transmission-gtk desktop=^8 follow=on
bspc rule -a Spotify desktop=^9 follow=on

"$HOME/mon.sh"


