#! /bin/bash
bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config focus_follows_pointer     true
bspc config focused_border_color      '#6699CC'
bspc config presel_feedback_color     '#FFCC66'
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config single_monocle            true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config auto_cancel               true

bspc rule -a Firefox          desktop=^2 follow=on
bspc rule -a google-chrome    desktop=^2 follow=on
bspc rule -a *:slack            desktop=^2 follow=on
bspc rule -a Thunar           desktop=^4 follow=on
bspc rule -a "IBM Notes"      desktop=^6 follow=on
bspc rule -a Skype            desktop=^7 split_dir=right  split_ratio=0.3
bspc rule -a VirtualBox       desktop=^5 follow=on
bspc rule -a Gimp             desktop=^5 follow=on
bspc rule -a Transmission-gtk desktop=^8 follow=on
bspc rule -a Spotify          desktop=^9 follow=on

bspc rule -a *:libreoffice      state=tiled

# Better if floating
bspc rule -a Keybase            state=floating
bspc rule -a Orage              state=floating
bspc rule -a Xfce4-appfinder    state=floating

~/bin/mon.sh
