#! /bin/bash
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config focused_border_color      '#6699CC'
bspc config presel_feedback_color     '#FFCC66'
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config single_monocle            true
# bspc config pointer_follows_focus     true
bspc config pointer_follows_monitor   true
bspc config honor_size_hints          true

bspc rule -a "Firefox"          desktop=2 follow=on
bspc rule -a "*:google-chrome"  desktop=2 follow=on
bspc rule -a "*:slack"          desktop=3 follow=on
bspc rule -a "Thunar"           desktop=4 follow=on
bspc rule -a "VirtualBox"       desktop=5 follow=on
bspc rule -a "IBM Notes"        desktop=6 follow=on
bspc rule -a "Gimp"             desktop=6 follow=on
bspc rule -a "Skype"            desktop=7 split_dir=right  split_ratio=0.3
bspc rule -a "Spotify"          desktop=9 follow=on
bspc rule -a "Steam"            desktop=0 split_ratio=0.3

# Enforce tiled
bspc rule -a "*:libreoffice"      state=tiled

# Better if floating
bspc rule -a "Keybase"            state=floating
bspc rule -a "Orage"              state=floating
bspc rule -a "Xfce4-appfinder"    state=floating
bspc rule -a "*:vpnui"            state=floating

# Configure desktop
~/.xstart
