#!/usr/bin/env bash

source "$HOME/.theme.bashrc"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        3
bspc config window_gap          5
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio               0.50
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config presel_feedback_color     "${theme_html_color10}"
bspc config normal_border_color       "${theme_html_color0}"
bspc config focused_border_color      "${theme_html_color3}"
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config single_monocle            true
bspc config pointer_follows_monitor   true
bspc config honor_size_hints          true
bspc config initial_polarity          second_child
bspc config external_rules_command    "$HOME/bin/bspwm-external-rules.sh"

bspc rule -a "*:gimp-2.8"       desktop=6 follow=on
bspc rule -a "*:google-chrome"  desktop=2 follow=on
bspc rule -a "*:skype"          desktop=8 follow=on
bspc rule -a "*:slack"          desktop=3 follow=on
bspc rule -a "Firefox"          desktop=2 follow=on
bspc rule -a "Steam"            desktop=0 follow=on
bspc rule -a "Thunar"           desktop=4 follow=on
bspc rule -a "VirtualBox"       desktop=5 follow=on
bspc rule -a "Vivaldi-stable"   desktop=2 follow=on

# Enforce tiled
bspc rule -a "*:libreoffice"    state=tiled

# Better if floating
bspc rule -a "*:vpnui"          state=floating
bspc rule -a "Keybase"          state=floating
bspc rule -a "Orage"            state=floating
bspc rule -a "Xfce4-appfinder"  state=floating sticky=on
bspc rule -a "peek"             state=floating

# Configure desktop
~/.xstart
