#!/usr/bin/bash

bspc config presel_feedback_color     "$(xrdb -query | awk '/^\*foreground:/{ print $2 }')"
bspc config normal_border_color       "$(xrdb -query | awk '/^\*background:/{ print $2 }')"
bspc config focused_border_color      "$(xrdb -query | awk '/^\*primary:/{ print $2 }')"
