--disable-features=Vulkan,WaylandPerSurfaceScale
--enable-features=WebRTCPipeWireCapturer,WaylandWindowDecorations,AllowQt,UseOzonePlatform,AcceleratedVideoDecodeLinuxGL,WaylandUiScale
--gtk-version=4
--high-dpi-support=1
--ozone-platform-hint=auto
--ozone-platform=wayland
